# Import modules
from neuroevolution.environments.other.xor_environment import XOREnvironment, XORWeightTrainingEnvironment
from neuroevolution.environments.openaigym.cartpole_environment import CartPoleEnvironment
